const alters = [
  { name: "Willow", role: "Creative Explorer", description: "Playful, imaginative, expresses feelings through sketches and concept art.", image: "https://picsum.photos/seed/Willow/800/600" },
  { name: "Atlas", role: "Protective Guardian", description: "Grounded, strong, appears with bold colors and powerful symbolism.", image: "https://picsum.photos/seed/Atlas/800/600" },
  { name: "Luna", role: "Quiet Dreamer", description: "Calm energy and soft, emotional artwork that feels like a night-time dream.", image: "https://picsum.photos/seed/Luna/800/600" },
  { name: "Ember", role: "Fiery Muse", description: "Passionate, impulsive, sparks vivid and energetic pieces.", image: "https://picsum.photos/seed/Ember/800/600" },
  { name: "Orion", role: "Wandering Storyteller", description: "Observant and curious, paints narrative-rich scenes.", image: "https://picsum.photos/seed/Orion/800/600" },
  { name: "Nova", role: "Bright Optimist", description: "Uplifting, uses light and color to convey hope.", image: "https://picsum.photos/seed/Nova/800/600" },
  { name: "Sage", role: "Quiet Analyst", description: "Thoughtful, detail-focused, prefers muted palettes and subtle textures.", image: "https://picsum.photos/seed/Sage/800/600" },
  { name: "Iris", role: "Color Alchemist", description: "Experimentative with hues and gradients to evoke feelings.", image: "https://picsum.photos/seed/Iris/800/600" },
  { name: "Kai", role: "Playful Minimalist", description: "Simple shapes, bold gestures, joyful compositions.", image: "https://picsum.photos/seed/Kai/800/600" },
  { name: "Rowan", role: "Grounded Poet", description: "Earthy textures and quiet portraiture with deep feeling.", image: "https://picsum.photos/seed/Rowan/800/600" },
  { name: "Zephyr", role: "Whimsical Drifter", description: "Light, breezy works that float between dream and day.", image: "https://picsum.photos/seed/Zephyr/800/600" },
  { name: "Echo", role: "Reflective Listener", description: "Introspective pieces that mirror internal dialogues.", image: "https://picsum.photos/seed/Echo/800/600" },
  { name: "Sol", role: "Radiant Performer", description: "Vivid, theatrical compositions that command attention.", image: "https://picsum.photos/seed/Sol/800/600" },
  { name: "Nox", role: "Nocturnal Thinker", description: "Works with shadow, contrast, and quiet intensity.", image: "https://picsum.photos/seed/Nox/800/600" },
  { name: "Mira", role: "Tender Caretaker", description: "Warm, nurturing imagery focused on comfort and safety.", image: "https://picsum.photos/seed/Mira/800/600" },
  { name: "Felix", role: "Mischievous Companion", description: "Playful mischief and upbeat sketches that lighten moods.", image: "https://picsum.photos/seed/Felix/800/600" },
  { name: "Nyx", role: "Mystic Seer", description: "Symbolic and mysterious works tapping into the subconscious.", image: "https://picsum.photos/seed/Nyx/800/600" },
  { name: "Aria", role: "Songful Narrator", description: "Musical rhythm in line and color; emotive and lyrical.", image: "https://picsum.photos/seed/Aria/800/600" },
  { name: "Kade", role: "Steady Builder", description: "Constructs order through pattern and strong composition.", image: "https://picsum.photos/seed/Kade/800/600" },
  { name: "Vale", role: "Reserved Companion", description: "Soft-spoken, supportive presence with gentle visuals.", image: "https://picsum.photos/seed/Vale/800/600" },
  { name: "Remy", role: "Curious Tinkerer", description: "Inventive, mixes media and found-object textures.", image: "https://picsum.photos/seed/Remy/800/600" },
  { name: "Talia", role: "Empathic Healer", description: "Soothing palettes and motifs that foster calm.", image: "https://picsum.photos/seed/Talia/800/600" },
  { name: "Rune", role: "Private Thinker", description: "Symbol-heavy, contemplative studies with layered meaning.", image: "https://picsum.photos/seed/Rune/800/600" },
  { name: "Blythe", role: "Sunny Imaginator", description: "Bright and carefree illustrations that uplift.", image: "https://picsum.photos/seed/Blythe/800/600" },
  { name: "Juno", role: "Bold Advocate", description: "Assertive, principled visuals with strong messaging.", image: "https://picsum.photos/seed/Juno/800/600" },
  { name: "Asher", role: "Quiet Strategist", description: "Measured, deliberate works that reveal structure.", image: "https://picsum.photos/seed/Asher/800/600" },
  { name: "Faye", role: "Gentle Wanderer", description: "Soft-focus scenes that travel through memory and feeling.", image: "https://picsum.photos/seed/Faye/800/600" },
  { name: "Theo", role: "Curious Analyst", description: "Observational pieces that examine form and function.", image: "https://picsum.photos/seed/Theo/800/600" },
];

const artPieces = [
  {
    title: "Inner Universe",
    artist: "Willow",
    description: "A mixed-media piece depicting the depth of an alter's emotional landscape.",
    image: "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Guardian Light",
    artist: "Atlas",
    description: "A bold composition using strong lines and luminous accents.",
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Moon Whisper",
    artist: "Luna",
    description: "A delicate study of color, mood, and reflective silence.",
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80",
  },
];
